export const mockRouteRecommendation = {
  method: 'semantic-groq-v2',
  goal: 'Desarrollar una aplicación web',
  explanation: '¡Hola! He organizado los cursos para que avances paso a paso hacia tu meta de desarrollar una aplicación web con .NET. Empezamos con los fundamentos de C#, luego profundizamos en pruebas y backend, avanzamos a Blazor para el front-end, y al final ampliamos tu perfil con Go y consolidas tu experiencia en Java/Spring. Cada curso está colocado justo cuando lo necesitas, sin crear dependencias imaginarias.',
  courses: [
    {
      courseId: 34,
      position: 1,
      title: 'C#: Empieza tu camino en el lenguaje',
      score: 0.8368,
      reason: 'Fundamentos de C#, esencial para tu objetivo de .NET y tu nivel principiante.',
      estimatedWeeks: 12,
    },
    {
      courseId: 20,
      position: 2,
      title: '.NET: Pruebas completas para minimal API',
      score: 0.8417,
      reason: 'Aprenderás a probar Minimal APIs, fortaleciendo tu backend en .NET y garantizando calidad desde el inicio.',
      estimatedWeeks: 6,
    },
    {
      courseId: 29,
      position: 3,
      title: '.NET Backend: .NET Core, SQL Server y seguridad JWT',
      score: 0.8351,
      reason: 'Construye APIs REST con seguridad JWT, EF Core y SQL Server, completando tus conocimientos de backend .NET.',
      estimatedWeeks: 11,
    },
    {
      courseId: 22,
      position: 4,
      title: 'Blazor: Desde cero con arquitectura limpia',
      score: 0.8644,
      reason: 'Con los fundamentos adquiridos, Blazor te permite crear una aplicación web full-stack con arquitectura limpia y UI moderna.',
      estimatedWeeks: 14,
    },
    {
      courseId: 2,
      position: 5,
      title: 'Golang: Backend Profesional',
      score: 0.6353,
      reason: 'Aunque tu objetivo es .NET, aprender Go te abre nuevas perspectivas de backend, reforzando tu versatilidad como desarrollador.',
      estimatedWeeks: 26,
    },
    {
      courseId: 24,
      position: 6,
      title: 'Java: Spring Boot - Guía definitiva',
      score: 0.6601,
      reason: 'Aprovecha tu experiencia en Java/Spring para consolidar habilidades y comparar enfoques, útil si trabajas con microservicios.',
      estimatedWeeks: 36,
    },
  ],
  refinementStatus: 'applied',
  model: 'openai/gpt-oss-20b',
};
