// <auto-generated />
using System;
using CodeQuest2026.Server.Infrastructure.DataSource.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeQuest2026.Server.Infrastructure.DataSource.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260915051101_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<DateOnly>("SourceVerifiedAt")
                        .HasColumnType("date")
                        .HasColumnName("source_verified_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("topics")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<string>("Track")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("track");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("courses_slug_key");

                    b.HasIndex("Track", "IsActive")
                        .HasDatabaseName("ix_courses_track_active");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_image_url", "image_url LIKE 'https://import.cdn.thinkific.com/%'");

                            t.HasCheckConstraint("ck_courses_level", "level IS NULL OR level IN ('Principiante', 'Intermedio', 'Avanzado')");

                            t.HasCheckConstraint("ck_courses_track", "track IN ('Fundamentos', 'Frontend', 'Backend', 'CSharp', 'Datos', 'IA', 'Movil', 'Herramientas', 'Automatizacion')");

                            t.HasCheckConstraint("ck_courses_url", "course_url LIKE 'https://cursos.devtalles.com/courses/%'");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
