// <auto-generated />
using System;
using CodeQuest2026.Server.Infrastructure.DataSource.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CodeQuest2026.Server.Infrastructure.DataSource.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927044619_AddCourseCatalogKinds")]
    partial class AddCourseCatalogKinds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CourseId"));

                    b.PrimitiveCollection<string[]>("CatalogKinds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("catalog_kinds")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("CourseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language");

                    b.PrimitiveCollection<string[]>("LearningOutcomes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("learning_outcomes")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("MetadataOrigin")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("metadata_origin");

                    b.Property<string>("MetadataSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("metadata_source_url");

                    b.Property<DateTime?>("MetadataVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_verified_at");

                    b.PrimitiveCollection<string[]>("Prerequisites")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("prerequisites")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("SkillsTaught")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("skills_taught")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<DateOnly>("SourceVerifiedAt")
                        .HasColumnType("date")
                        .HasColumnName("source_verified_at");

                    b.Property<string>("Syllabus")
                        .HasColumnType("text")
                        .HasColumnName("syllabus");

                    b.PrimitiveCollection<string[]>("TargetAudience")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("target_audience")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("topics")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("courses_slug_key");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_courses_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("IsActive", "Level")
                        .HasDatabaseName("ix_courses_is_active_level");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_catalog_kinds", "catalog_kinds <@ ARRAY['course', 'free', 'mini-course', 'pro-exclusive', 'legacy', 'in-development']::text[]");

                            t.HasCheckConstraint("ck_courses_duration_minutes", "duration_minutes IS NULL OR duration_minutes > 0");

                            t.HasCheckConstraint("ck_courses_image_url", "image_url LIKE 'https://import.cdn.thinkific.com/%'");

                            t.HasCheckConstraint("ck_courses_level", "level IS NULL OR level IN ('Principiante', 'Intermedio', 'Avanzado')");

                            t.HasCheckConstraint("ck_courses_url", "course_url LIKE 'https://cursos.devtalles.com/courses/%'");
                        });
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.CourseEmbedding", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.HasKey("CourseId")
                        .HasName("course_embeddings_pkey");

                    b.HasIndex("Model", "Dimensions")
                        .HasDatabaseName("ix_course_embeddings_model_dimensions");

                    b.ToTable("course_embeddings", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_embeddings_content_hash", "content_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_course_embeddings_dimensions", "dimensions > 0 AND vector_dims(embedding) = dimensions");

                            t.HasCheckConstraint("ck_course_embeddings_model", "length(btrim(model)) > 0");

                            t.HasCheckConstraint("ck_course_embeddings_nonzero", "(embedding <#> embedding) < 0");
                        });
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.LearningRoute", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("explanation");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("goal");

                    b.Property<string>("PreferencesSnapshot")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("preferences_snapshot");

                    b.Property<string>("RecommendationMethod")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("recommendation_method");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.HasKey("RouteId");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("learning_routes", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.LearningRouteCourse", b =>
                {
                    b.Property<Guid>("RouteId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_id");

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("ProgressPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("progress_percentage");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.HasKey("RouteId", "CourseId");

                    b.HasIndex("CourseId");

                    b.HasIndex("RouteId", "Position")
                        .IsUnique();

                    b.ToTable("learning_route_courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_learning_route_courses_position", "position > 0");

                            t.HasCheckConstraint("ck_learning_route_courses_progress", "progress_percentage BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("TagId")
                        .HasName("tags_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Avatar")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("avatar");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscordId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("discord_id");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("DiscordId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_discord_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.UserExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "ProviderUserId");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("user_external_logins", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.UserPreference", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)")
                        .HasColumnName("user_id");

                    b.PrimitiveCollection<string[]>("ExistingSkills")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("existing_skills");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("experience_level");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("goal");

                    b.PrimitiveCollection<string[]>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("interests");

                    b.Property<int?>("MinutesPerWeek")
                        .HasColumnType("integer")
                        .HasColumnName("minutes_per_week");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("preferred_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_preferences_minutes_per_week", "minutes_per_week IS NULL OR minutes_per_week > 0");
                        });
                });

            modelBuilder.Entity("CourseCategory", b =>
                {
                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.HasKey("course_id", "category_id")
                        .HasName("course_categories_pkey");

                    b.HasIndex("category_id", "course_id")
                        .HasDatabaseName("ix_course_categories_category_id_course_id");

                    b.ToTable("course_categories", (string)null);
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("tag_id")
                        .HasColumnType("bigint");

                    b.HasKey("course_id", "tag_id")
                        .HasName("course_tags_pkey");

                    b.HasIndex("tag_id", "course_id")
                        .HasDatabaseName("ix_course_tags_tag_id_course_id");

                    b.ToTable("course_tags", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.CourseEmbedding", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", "Course")
                        .WithOne("Embedding")
                        .HasForeignKey("CodeQuest2026.Server.Infrastructure.DataSource.Entities.CourseEmbedding", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.LearningRoute", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.User", "User")
                        .WithMany("Routes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.LearningRouteCourse", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.LearningRoute", "Route")
                        .WithMany("Courses")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.UserExternalLogin", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.User", "User")
                        .WithMany("ExternalLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.UserPreference", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("CodeQuest2026.Server.Infrastructure.DataSource.Entities.UserPreference", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CourseCategory", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", b =>
                {
                    b.Navigation("Embedding");
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.LearningRoute", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.User", b =>
                {
                    b.Navigation("ExternalLogins");

                    b.Navigation("Preferences");

                    b.Navigation("Routes");
                });
#pragma warning restore 612, 618
        }
    }
}
