using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CodeQuest2026.Server.Infrastructure.DataSource.Migrations;

// Frozen seed for this migration. Future catalog changes belong in a new migration.
public partial class AddCourseCategoriesAndTags
{
    private static void SeedCatalog(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(
            """
            -- Clasificación editorial basada en los títulos y tracks de Seed Courses.sql.
            -- No supone una revisión del temario completo. Asociaciones por slug, sin IDs fijos.
            INSERT INTO categories (slug, name) VALUES
            ('fundamentos', 'Fundamentos'),
            ('frontend', 'Frontend'),
            ('backend', 'Backend'),
            ('csharp', 'C# y .NET'),
            ('datos', 'Datos'),
            ('ia', 'Inteligencia artificial'),
            ('movil', 'Desarrollo móvil'),
            ('herramientas', 'Herramientas'),
            ('automatizacion', 'Automatización')
            ON CONFLICT (slug) DO NOTHING;
            
            INSERT INTO tags (slug, name) VALUES
            ('accesibilidad', 'Accesibilidad'),
            ('agentes-ia', 'Agentes de IA'),
            ('android', 'Android'),
            ('angular', 'Angular'),
            ('apis', 'APIs'),
            ('arquitectura-de-software', 'Arquitectura de software'),
            ('arquitectura-hexagonal', 'Arquitectura hexagonal'),
            ('asistentes-ia', 'Asistentes de IA'),
            ('astro', 'Astro'),
            ('autenticacion', 'Autenticación'),
            ('automatizacion', 'Automatización'),
            ('aws', 'AWS'),
            ('blazor', 'Blazor'),
            ('bloc', 'BLoC'),
            ('bun', 'Bun'),
            ('claude-api', 'Claude API'),
            ('claude-code', 'Claude Code'),
            ('clean-architecture', 'Clean Architecture'),
            ('clean-code', 'Clean Code'),
            ('componentes-ui', 'Componentes de UI'),
            ('composition-api', 'Composition API'),
            ('concurrencia', 'Concurrencia'),
            ('contenedores', 'Contenedores'),
            ('control-de-versiones', 'Control de versiones'),
            ('csharp', 'C#'),
            ('css', 'CSS'),
            ('dart', 'Dart'),
            ('django', 'Django'),
            ('docker', 'Docker'),
            ('dotnet', '.NET'),
            ('enrutamiento', 'Enrutamiento'),
            ('expo', 'Expo'),
            ('fastapi', 'FastAPI'),
            ('flutter', 'Flutter'),
            ('flutter-web', 'Flutter Web'),
            ('fundamentos-de-programacion', 'Fundamentos de programación'),
            ('gemini', 'Gemini'),
            ('gestion-de-estado', 'Gestión de estado'),
            ('git', 'Git'),
            ('github', 'GitHub'),
            ('go', 'Go'),
            ('graphql', 'GraphQL'),
            ('ingenieria-de-prompts', 'Ingeniería de prompts'),
            ('inteligencia-artificial', 'Inteligencia artificial'),
            ('ios', 'iOS'),
            ('java', 'Java'),
            ('javascript', 'JavaScript'),
            ('jwt', 'JWT'),
            ('laravel', 'Laravel'),
            ('llm', 'LLM'),
            ('mcp', 'MCP'),
            ('microservicios', 'Microservicios'),
            ('minimal-api', 'Minimal API'),
            ('mvc', 'MVC'),
            ('n8n', 'n8n'),
            ('nestjs', 'NestJS'),
            ('nextjs', 'Next.js'),
            ('ngmodules', 'NgModules'),
            ('nodejs', 'Node.js'),
            ('nuxt', 'Nuxt'),
            ('openai', 'OpenAI'),
            ('opencode', 'OpenCode'),
            ('options-api', 'Options API'),
            ('patrones-de-diseno', 'Patrones de diseño'),
            ('pdf', 'PDF'),
            ('php', 'PHP'),
            ('postgresql', 'PostgreSQL'),
            ('programacion-reactiva', 'Programación reactiva'),
            ('pruebas-e2e', 'Pruebas end to end'),
            ('pruebas-unitarias', 'Pruebas unitarias'),
            ('python', 'Python'),
            ('qwik', 'Qwik'),
            ('rag', 'RAG'),
            ('react', 'React'),
            ('react-native', 'React Native'),
            ('react-router', 'React Router'),
            ('recursos-nativos', 'Recursos nativos'),
            ('reportes', 'Reportes'),
            ('repository-pattern', 'Repository Pattern'),
            ('rest', 'REST'),
            ('riverpod', 'Riverpod'),
            ('shadcn-ui', 'shadcn/ui'),
            ('solid', 'SOLID'),
            ('spring-ai', 'Spring AI'),
            ('spring-boot', 'Spring Boot'),
            ('sql', 'SQL'),
            ('sql-server', 'SQL Server'),
            ('tailwind-css', 'Tailwind CSS'),
            ('tanstack-query', 'TanStack Query'),
            ('testing', 'Testing'),
            ('typescript', 'TypeScript'),
            ('vibe-coding', 'Vibe Coding'),
            ('vscode', 'Visual Studio Code'),
            ('vue', 'Vue.js'),
            ('websockets', 'WebSockets'),
            ('zustand', 'Zustand')
            ON CONFLICT (slug) DO NOTHING;
            
            INSERT INTO course_categories (course_id, category_id)
            SELECT courses.course_id, categories.category_id
            FROM (VALUES
            ('git-github-control-versiones-desde-cero', 'fundamentos'),
            ('golang-backend-profesional', 'backend'),
            ('laravel-ai', 'backend'),
            ('laravel-ai', 'ia'),
            ('spring-ai', 'ia'),
            ('spring-ai', 'backend'),
            ('open-code-guia-completa', 'herramientas'),
            ('open-code-guia-completa', 'ia'),
            ('claude-code-guia-completa', 'herramientas'),
            ('claude-code-guia-completa', 'ia'),
            ('ia-para-developers', 'ia'),
            ('ia-para-developers', 'backend'),
            ('python-ia-aplicada', 'ia'),
            ('spring-boot-patrones-arquitectura', 'backend'),
            ('ingenieria-de-prompts', 'ia'),
            ('vibe-coding', 'ia'),
            ('golang-fundamentos-lenguaje', 'fundamentos'),
            ('php-moderno', 'fundamentos'),
            ('spring-boot-microservicios', 'backend'),
            ('angular-sockets-bun', 'frontend'),
            ('react-sockets', 'frontend'),
            ('tailwindcss-para-desarrolladores', 'frontend'),
            ('python-n8n-automatiza-rutinas', 'automatizacion'),
            ('springboot-mvc-hexagonal', 'backend'),
            ('net-pruebascompletas', 'csharp'),
            ('net-pruebascompletas', 'backend'),
            ('nuxt', 'frontend'),
            ('netfullstack', 'csharp'),
            ('netfullstack', 'frontend'),
            ('fastapi', 'backend'),
            ('spring-boot', 'backend'),
            ('n8n-mcp', 'automatizacion'),
            ('n8n-mcp', 'ia'),
            ('react-de-cero', 'frontend'),
            ('expo-gemini', 'movil'),
            ('expo-gemini', 'ia'),
            ('java-avanzado', 'backend'),
            ('net-backend', 'csharp'),
            ('net-backend', 'backend'),
            ('net-backend', 'datos'),
            ('django', 'backend'),
            ('flutter-gemini', 'movil'),
            ('flutter-gemini', 'ia'),
            ('react-router', 'frontend'),
            ('python', 'fundamentos'),
            ('csharp', 'csharp'),
            ('csharp', 'fundamentos'),
            ('java', 'fundamentos'),
            ('nestjs-testing', 'backend'),
            ('angular-moderno', 'frontend'),
            ('patrones-diseno', 'fundamentos'),
            ('react-native-expo', 'movil'),
            ('angular-pro', 'frontend'),
            ('astro', 'frontend'),
            ('nestjs-reportes', 'backend'),
            ('shadcn-ui', 'frontend'),
            ('vue-cero-a-experto', 'frontend'),
            ('nestjs-microservicios', 'backend'),
            ('openai-angular-nestjs', 'ia'),
            ('openai-angular-nestjs', 'frontend'),
            ('openai-angular-nestjs', 'backend'),
            ('openai-react-nestjs', 'ia'),
            ('openai-react-nestjs', 'frontend'),
            ('openai-react-nestjs', 'backend'),
            ('zustand-react', 'frontend'),
            ('node-clean-architecture', 'backend'),
            ('flutter-bloc', 'movil'),
            ('nodejs-de-cero-a-experto', 'backend'),
            ('riverpod-con-anotaciones', 'movil'),
            ('sql-con-postgres', 'datos'),
            ('nextjs', 'frontend'),
            ('qwik-introduccion', 'frontend'),
            ('flutter-movil-intermedio', 'movil'),
            ('flutter-movil-cero-a-experto', 'movil'),
            ('angular-clasico', 'frontend'),
            ('docker-guia-practica', 'herramientas'),
            ('nest-graphql', 'backend'),
            ('programacion-para-principiantes', 'fundamentos'),
            ('nest', 'backend'),
            ('legacy-vue-options-api', 'frontend'),
            ('tanstack-query', 'frontend'),
            ('legacy-flutter-web', 'movil'),
            ('legacy-flutter-web', 'frontend'),
            ('visual-studio-code', 'herramientas'),
            ('dart-cero-hasta-detalles', 'fundamentos'),
            ('javascript-moderno', 'fundamentos'),
            ('legacy-git-github', 'herramientas'),
            ('typescript-guia-completa', 'fundamentos'),
            ('react-pro', 'frontend'),
            ('solid-clean-code', 'fundamentos')
            ) AS seed(course_slug, category_slug)
            JOIN courses ON courses.slug = seed.course_slug
            JOIN categories ON categories.slug = seed.category_slug
            ON CONFLICT (course_id, category_id) DO NOTHING;
            
            INSERT INTO course_tags (course_id, tag_id)
            SELECT courses.course_id, tags.tag_id
            FROM (VALUES
            ('git-github-control-versiones-desde-cero', 'git'),
            ('git-github-control-versiones-desde-cero', 'github'),
            ('git-github-control-versiones-desde-cero', 'control-de-versiones'),
            ('golang-backend-profesional', 'go'),
            ('laravel-ai', 'laravel'),
            ('laravel-ai', 'php'),
            ('laravel-ai', 'inteligencia-artificial'),
            ('laravel-ai', 'rest'),
            ('laravel-ai', 'jwt'),
            ('laravel-ai', 'repository-pattern'),
            ('spring-ai', 'spring-ai'),
            ('spring-ai', 'java'),
            ('spring-ai', 'inteligencia-artificial'),
            ('spring-ai', 'llm'),
            ('spring-ai', 'rag'),
            ('spring-ai', 'agentes-ia'),
            ('spring-ai', 'aws'),
            ('open-code-guia-completa', 'opencode'),
            ('open-code-guia-completa', 'inteligencia-artificial'),
            ('claude-code-guia-completa', 'claude-code'),
            ('claude-code-guia-completa', 'inteligencia-artificial'),
            ('ia-para-developers', 'claude-api'),
            ('ia-para-developers', 'rag'),
            ('ia-para-developers', 'agentes-ia'),
            ('ia-para-developers', 'nodejs'),
            ('ia-para-developers', 'inteligencia-artificial'),
            ('python-ia-aplicada', 'python'),
            ('python-ia-aplicada', 'inteligencia-artificial'),
            ('spring-boot-patrones-arquitectura', 'spring-boot'),
            ('spring-boot-patrones-arquitectura', 'java'),
            ('spring-boot-patrones-arquitectura', 'arquitectura-de-software'),
            ('ingenieria-de-prompts', 'ingenieria-de-prompts'),
            ('ingenieria-de-prompts', 'inteligencia-artificial'),
            ('vibe-coding', 'vibe-coding'),
            ('vibe-coding', 'inteligencia-artificial'),
            ('golang-fundamentos-lenguaje', 'go'),
            ('golang-fundamentos-lenguaje', 'fundamentos-de-programacion'),
            ('php-moderno', 'php'),
            ('php-moderno', 'fundamentos-de-programacion'),
            ('spring-boot-microservicios', 'spring-boot'),
            ('spring-boot-microservicios', 'java'),
            ('spring-boot-microservicios', 'microservicios'),
            ('angular-sockets-bun', 'angular'),
            ('angular-sockets-bun', 'websockets'),
            ('angular-sockets-bun', 'bun'),
            ('react-sockets', 'react'),
            ('react-sockets', 'websockets'),
            ('react-sockets', 'bun'),
            ('tailwindcss-para-desarrolladores', 'tailwind-css'),
            ('tailwindcss-para-desarrolladores', 'css'),
            ('python-n8n-automatiza-rutinas', 'python'),
            ('python-n8n-automatiza-rutinas', 'n8n'),
            ('python-n8n-automatiza-rutinas', 'automatizacion'),
            ('springboot-mvc-hexagonal', 'spring-boot'),
            ('springboot-mvc-hexagonal', 'java'),
            ('springboot-mvc-hexagonal', 'mvc'),
            ('springboot-mvc-hexagonal', 'arquitectura-hexagonal'),
            ('net-pruebascompletas', 'dotnet'),
            ('net-pruebascompletas', 'csharp'),
            ('net-pruebascompletas', 'testing'),
            ('net-pruebascompletas', 'minimal-api'),
            ('nuxt', 'nuxt'),
            ('nuxt', 'vue'),
            ('netfullstack', 'blazor'),
            ('netfullstack', 'dotnet'),
            ('netfullstack', 'csharp'),
            ('netfullstack', 'clean-architecture'),
            ('fastapi', 'fastapi'),
            ('fastapi', 'python'),
            ('fastapi', 'apis'),
            ('spring-boot', 'spring-boot'),
            ('spring-boot', 'java'),
            ('n8n-mcp', 'n8n'),
            ('n8n-mcp', 'mcp'),
            ('n8n-mcp', 'automatizacion'),
            ('n8n-mcp', 'agentes-ia'),
            ('n8n-mcp', 'inteligencia-artificial'),
            ('react-de-cero', 'react'),
            ('expo-gemini', 'expo'),
            ('expo-gemini', 'gemini'),
            ('expo-gemini', 'inteligencia-artificial'),
            ('java-avanzado', 'java'),
            ('java-avanzado', 'programacion-reactiva'),
            ('java-avanzado', 'concurrencia'),
            ('java-avanzado', 'patrones-de-diseno'),
            ('net-backend', 'dotnet'),
            ('net-backend', 'csharp'),
            ('net-backend', 'sql-server'),
            ('net-backend', 'jwt'),
            ('net-backend', 'autenticacion'),
            ('django', 'django'),
            ('django', 'python'),
            ('flutter-gemini', 'flutter'),
            ('flutter-gemini', 'gemini'),
            ('flutter-gemini', 'inteligencia-artificial'),
            ('react-router', 'react'),
            ('react-router', 'react-router'),
            ('react-router', 'enrutamiento'),
            ('python', 'python'),
            ('python', 'fundamentos-de-programacion'),
            ('csharp', 'csharp'),
            ('csharp', 'fundamentos-de-programacion'),
            ('java', 'java'),
            ('java', 'fundamentos-de-programacion'),
            ('nestjs-testing', 'nestjs'),
            ('nestjs-testing', 'testing'),
            ('nestjs-testing', 'pruebas-unitarias'),
            ('nestjs-testing', 'pruebas-e2e'),
            ('angular-moderno', 'angular'),
            ('patrones-diseno', 'patrones-de-diseno'),
            ('react-native-expo', 'react-native'),
            ('react-native-expo', 'react'),
            ('react-native-expo', 'expo'),
            ('react-native-expo', 'ios'),
            ('react-native-expo', 'android'),
            ('angular-pro', 'angular'),
            ('astro', 'astro'),
            ('nestjs-reportes', 'nestjs'),
            ('nestjs-reportes', 'nodejs'),
            ('nestjs-reportes', 'pdf'),
            ('nestjs-reportes', 'reportes'),
            ('shadcn-ui', 'shadcn-ui'),
            ('shadcn-ui', 'accesibilidad'),
            ('shadcn-ui', 'componentes-ui'),
            ('vue-cero-a-experto', 'vue'),
            ('vue-cero-a-experto', 'composition-api'),
            ('nestjs-microservicios', 'nestjs'),
            ('nestjs-microservicios', 'microservicios'),
            ('openai-angular-nestjs', 'openai'),
            ('openai-angular-nestjs', 'angular'),
            ('openai-angular-nestjs', 'nestjs'),
            ('openai-angular-nestjs', 'inteligencia-artificial'),
            ('openai-angular-nestjs', 'asistentes-ia'),
            ('openai-react-nestjs', 'openai'),
            ('openai-react-nestjs', 'react'),
            ('openai-react-nestjs', 'nestjs'),
            ('openai-react-nestjs', 'inteligencia-artificial'),
            ('openai-react-nestjs', 'asistentes-ia'),
            ('zustand-react', 'zustand'),
            ('zustand-react', 'react'),
            ('zustand-react', 'gestion-de-estado'),
            ('node-clean-architecture', 'nodejs'),
            ('node-clean-architecture', 'autenticacion'),
            ('node-clean-architecture', 'rest'),
            ('node-clean-architecture', 'clean-architecture'),
            ('flutter-bloc', 'flutter'),
            ('flutter-bloc', 'bloc'),
            ('flutter-bloc', 'gestion-de-estado'),
            ('nodejs-de-cero-a-experto', 'nodejs'),
            ('riverpod-con-anotaciones', 'riverpod'),
            ('riverpod-con-anotaciones', 'gestion-de-estado'),
            ('sql-con-postgres', 'sql'),
            ('sql-con-postgres', 'postgresql'),
            ('nextjs', 'nextjs'),
            ('nextjs', 'react'),
            ('qwik-introduccion', 'qwik'),
            ('flutter-movil-intermedio', 'flutter'),
            ('flutter-movil-intermedio', 'recursos-nativos'),
            ('flutter-movil-cero-a-experto', 'flutter'),
            ('angular-clasico', 'angular'),
            ('angular-clasico', 'ngmodules'),
            ('docker-guia-practica', 'docker'),
            ('docker-guia-practica', 'contenedores'),
            ('nest-graphql', 'nestjs'),
            ('nest-graphql', 'graphql'),
            ('nest-graphql', 'apis'),
            ('programacion-para-principiantes', 'fundamentos-de-programacion'),
            ('nest', 'nestjs'),
            ('nest', 'nodejs'),
            ('legacy-vue-options-api', 'vue'),
            ('legacy-vue-options-api', 'options-api'),
            ('tanstack-query', 'tanstack-query'),
            ('tanstack-query', 'gestion-de-estado'),
            ('legacy-flutter-web', 'flutter'),
            ('legacy-flutter-web', 'flutter-web'),
            ('visual-studio-code', 'vscode'),
            ('dart-cero-hasta-detalles', 'dart'),
            ('dart-cero-hasta-detalles', 'fundamentos-de-programacion'),
            ('javascript-moderno', 'javascript'),
            ('javascript-moderno', 'fundamentos-de-programacion'),
            ('legacy-git-github', 'git'),
            ('legacy-git-github', 'github'),
            ('legacy-git-github', 'control-de-versiones'),
            ('typescript-guia-completa', 'typescript'),
            ('react-pro', 'react'),
            ('solid-clean-code', 'solid'),
            ('solid-clean-code', 'clean-code')
            ) AS seed(course_slug, tag_slug)
            JOIN courses ON courses.slug = seed.course_slug
            JOIN tags ON tags.slug = seed.tag_slug
            ON CONFLICT (course_id, tag_id) DO NOTHING;
            """);
    }
}

