// <auto-generated />
using System;
using CodeQuest2026.Server.Infrastructure.DataSource.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CodeQuest2026.Server.Infrastructure.DataSource.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Category", b =>
                {
                    b.Property<long>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("CategoryId")
                        .HasName("categories_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_slug");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", b =>
                {
                    b.Property<long>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("CourseId"));

                    b.Property<string>("CourseUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ImageAlt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("image_alt");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language");

                    b.PrimitiveCollection<string[]>("LearningOutcomes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("learning_outcomes")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Level")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<string>("MetadataOrigin")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("metadata_origin");

                    b.Property<string>("MetadataSourceUrl")
                        .HasColumnType("text")
                        .HasColumnName("metadata_source_url");

                    b.Property<DateTime?>("MetadataVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("metadata_verified_at");

                    b.PrimitiveCollection<string[]>("Prerequisites")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("prerequisites")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.PrimitiveCollection<string[]>("SkillsTaught")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("skills_taught")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("slug");

                    b.Property<DateOnly>("SourceVerifiedAt")
                        .HasColumnType("date")
                        .HasColumnName("source_verified_at");

                    b.Property<string>("Syllabus")
                        .HasColumnType("text")
                        .HasColumnName("syllabus");

                    b.PrimitiveCollection<string[]>("TargetAudience")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("target_audience")
                        .HasDefaultValueSql("ARRAY[]::text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("topics")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("CourseId")
                        .HasName("courses_pkey");

                    b.HasAlternateKey("Slug")
                        .HasName("courses_slug_key");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_courses_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("IsActive", "Level")
                        .HasDatabaseName("ix_courses_is_active_level");

                    b.ToTable("courses", null, t =>
                        {
                            t.HasCheckConstraint("ck_courses_duration_minutes", "duration_minutes IS NULL OR duration_minutes > 0");

                            t.HasCheckConstraint("ck_courses_image_url", "image_url LIKE 'https://import.cdn.thinkific.com/%'");

                            t.HasCheckConstraint("ck_courses_level", "level IS NULL OR level IN ('Principiante', 'Intermedio', 'Avanzado')");

                            t.HasCheckConstraint("ck_courses_url", "course_url LIKE 'https://cursos.devtalles.com/courses/%'");
                        });
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.CourseEmbedding", b =>
                {
                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.HasKey("CourseId")
                        .HasName("course_embeddings_pkey");

                    b.HasIndex("Model", "Dimensions")
                        .HasDatabaseName("ix_course_embeddings_model_dimensions");

                    b.ToTable("course_embeddings", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_embeddings_content_hash", "content_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_course_embeddings_dimensions", "dimensions > 0 AND vector_dims(embedding) = dimensions");

                            t.HasCheckConstraint("ck_course_embeddings_model", "length(btrim(model)) > 0");

                            t.HasCheckConstraint("ck_course_embeddings_nonzero", "(embedding <#> embedding) < 0");
                        });
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Tag", b =>
                {
                    b.Property<long>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("TagId")
                        .HasName("tags_pkey");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_slug");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("CourseCategory", b =>
                {
                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("category_id")
                        .HasColumnType("bigint");

                    b.HasKey("course_id", "category_id")
                        .HasName("course_categories_pkey");

                    b.HasIndex("category_id", "course_id")
                        .HasDatabaseName("ix_course_categories_category_id_course_id");

                    b.ToTable("course_categories", (string)null);
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.Property<long>("course_id")
                        .HasColumnType("bigint");

                    b.Property<long>("tag_id")
                        .HasColumnType("bigint");

                    b.HasKey("course_id", "tag_id")
                        .HasName("course_tags_pkey");

                    b.HasIndex("tag_id", "course_id")
                        .HasDatabaseName("ix_course_tags_tag_id_course_id");

                    b.ToTable("course_tags", (string)null);
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.CourseEmbedding", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", "Course")
                        .WithOne("Embedding")
                        .HasForeignKey("CodeQuest2026.Server.Infrastructure.DataSource.Entities.CourseEmbedding", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("CourseCategory", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourseTag", b =>
                {
                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("tag_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeQuest2026.Server.Infrastructure.DataSource.Entities.Course", b =>
                {
                    b.Navigation("Embedding");
                });
#pragma warning restore 612, 618
        }
    }
}
